### ISSUE TITLE
Boostrap earlier PolyfilledHTMLTemplateElement.bootstrap

### ISSUE THREAD

**Issue by GrosSacASac** [manubb/template#1]
This template polyfill is awesome.

I have a problem with code that relies on `document.importNode` and `template.content` to be executed before the document is loaded: it will not work.

Even if the `template.js` runs before.

The reason is that  `PolyfilledHTMLTemplateElement.bootstrap(document);` is called inside `DOMContentLoaded `callback.

I propose to call it **immediately** instead.

In cases where `<script>` is at the end of the body, (best practice anyway) it will not change anything. In case , when `importNode` needs to be called slightly earlier it will now work too.

**Comment by manubb** [comment]
I do not see clearly your point but if you load the polyfill before, you can add a call to `bootstrap` before the `DOMContentLoaded` event:
```js
if (window.HTMLTemplateElement.bootstrap) window.HTMLTemplateElement.bootstrap(document);
```
so that you can use the polyfill earlier. I do not think that changing the polyfill the way you suggest is a good idea by the way. Another solution could be to wait for `DOMContentLoaded` event before executing your code.

**Comment by GrosSacASac** [comment]
thanks
